# Generated by Django 6.0.4 on 2026-05-04 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(
                choices=[
                    ('purchase', 'Purchase'),
                    ('sell', 'Sell'),
                    ('return', 'Return'),
                    ('adjustment', 'Adjustment'),
                    ('transfer', 'Transfer'),
                ],
                max_length=20,
            ),
        ),
    ]

